<?php
$product = $block->getProduct();
if ($product != Null && $product->getData('promotion_text') !=Null) {
    $text = $product->getData('promotion_text');
    $interval = $product->getData('promotion_interval');
}
?>

<span id="element-id" data-interval="<?=isset($interval) ? $interval : Null ?>" style="display: none"></span>
<div id="modal-content"  data-mage-init='{"interval-modal": {"target": "#modal-content"}}'>
<?=  isset($text) ? $text : ''?>
</div>
