<?php


$product = $block->getProduct();

if ($product != Null && $product->getData('promotion_text') !=Null) {

    $text = $product->getData('promotion_text');
    $interval = $product->getData('promotion_interval');

    echo <<<HTML
<span id="element-id" data-interval="$interval" style="display: none"></span>
<div id="modal-content"  data-mage-init='{"interval-modal": {"target": "#modal-content"}}'>
 "{$text}"
</div>
HTML;
}

?>









